### ISSUE TITLE
Replacing session token for local storage access token.

### ISSUE THREAD

**Issue by alexvais** [yireo/Yireo_SyncGraphQlSessionWithFrontend#1]
Will be a good practice replace Magento 2 session token with a Local Storage access token for customer APIs?

Do you have any solution about "refresh token" in order to do not have a long-life access token for every customer? or could be a good practice change the expiration time for customer access token to infinite or maybe 1 year and store it in local storage of the browser in order to do the API self requests? that can also could be a question in order to create an mobile APP and how to manage that access token.

**Comment by jissereitsma** [comment]
Thanks for posting. First of all, do I understand it correctly that you're not having an issue with this extension, but just have general questions about the tokens in the Magento 2 GraphQl API? Normally GitHub issues like these are really reserved for improving software, while the working of the Magento GraphQL API is best moved to a Slack channel like Magento Community Engineering or likewise.

Anyway, I'm not sure whether it classifies as any kind of "practice" to move a GraphQL token to Local Storage. I'm not sure if anyone but Hyva (https://github.com/hyva-themes/magento2-graphql-tokens) has done the same thing. Note however that the token is not the same as the session ID. And the same token could have been part of a React or Vue app and stored in Local Storage as well (see the sources of Magento PWA Studio). So it is a common practice to store session keys in a browser with an SPA architecture. I'm not sure how this would relate to a best practice and how this compares to cookies.

As for the refreshing of tokens, it is partially built into the GraphQL API. It would not be part of this module to mess with that, but if you spot issues there, it would be best to address this to the Magento 2 GraphQL team? Refreshing more often sounds cool so why not work on improving Magento here?

**Comment by alexvais** [comment]
hey @jissereitsma i didn't know about the Slack, i just joined in. Really thanks.

And sorry about the question, i know that it is not a bug. I will close this and continue in Slack! 

Also thanks for the Reference of hyva tokens

thanks!!
